import { wagmiClient } from "./config/wagmi";
import "./globals.css";
import { WagmiConfig } from "wagmi";
import { ConnectKitProvider, SIWESession } from "connectkit";
import { siweClient } from "@/app/config/siweClient";
import { ClientProvider } from "@/app/config/trpc";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WagmiConfig client={wagmiClient}>
          <siweClient.Provider
            // Optional parameters
            enabled={true} // defaults true
            nonceRefetchInterval={300000} // in milliseconds, defaults to 5 minutes
            sessionRefetchInterval={300000} // in milliseconds, defaults to 5 minutes
            signOutOnDisconnect={true} // defaults true
            signOutOnAccountChange={true} // defaults true
            signOutOnNetworkChange={true} // defaults true
            onSignIn={(session?: SIWESession) => {}}
            onSignOut={() => {}}
          >
            <ClientProvider>
              <ConnectKitProvider>{children}</ConnectKitProvider>
            </ClientProvider>
          </siweClient.Provider>
        </WagmiConfig>
      </body>
    </html>
  );
}
